---
spring:
  config:
    activate:
      on-profile: local
cors:
  mapping: /**
  allowedOrigins: http://localhost:3000, http://localhost:8080
logging:
  level:
    root: debug
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: debug
---
spring:
  config:
    activate:
      on-profile: production
logging:
  level:
    root: info