spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
cors:
  mapping: "/**"
  allowedOrigins: "*"
logging:
  level:
    root: debug
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
cors:
  mapping: "/**"
  allowedOrigins: "*"
logging:
  level:
    root: debug
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: production
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: info
server:
  port: 8080