---
spring:
  config:
    activate:
      on-profile: local
cors:
  mapping: /**
  allowedOrigins: ["http://localhost:3000/", "http://localhost:8080"]
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: production