spring:
  config:
    activate:
      on-profile: local
cors:
  mapping: /**
  allowedOrigins: http://localhost:3000, http://localhost:8080, http://localhost
logging:
  level:
    root: debug
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev
cors:
  mapping: /**
  allowedOrigins: http://34.64.211.184:80, http://localhost
logging:
  level:
    root: debug
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: production
logging:
  level:
    root: info
server:
  port: 8080