# Generated by Django 3.2.4 on 2021-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selfIntroduce',
            fields=[
                ('userId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('userImage', models.URLField(max_length=2000)),
                ('subject', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
